language:
  - scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8
env:
  - TEST_DIR=REST
  - TEST_DIR=DatabaseLogic
sudo:
  - required
script:
  - cd $TEST_DIR && sbt assembly && sbt clean coverage test coverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
services:
  - cassandra
before_install:
  - sudo service cassandra start
  - sleep 5
