language:
  - scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8
sudo:
  - required
script:
  - sbt assembly && sbt clean coverage test coverageReport
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.m2/repository
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
before_install:
  - sudo rm -rf /var/lib/cassandra/*
  - wget http://www.us.apache.org/dist/cassandra/3.0.12/apache-cassandra-3.0.12-bin.tar.gz && tar -xvzf apache-cassandra-3.0.12-bin.tar.gz && sudo sh apache-cassandra-3.0.12/bin/cassandra
  - sudo service cassandra start
